sudo: required
services:
    - docker

before_install:
  - docker build -t victoramaya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true victoramaya/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env" 
  bucket_name: "elasticbeanstalk-us-west-2-432543"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY