FROM node:alpine as builder
WORKDIR '/app'
COPY ./package.json ./
CMD ["npm","install"]
COPY . .
CMD ["npm","run","build"]

FROM nginx 
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /user/shre/nginx/html