language: generic
sudo: required
services:
 - docker
before_build:
  - docker build -t vamaya/react-test -f ./client/Dockerfile.dev ./client
 
script: 
  - docker run -e CI=true vamaya/react-test npm test
 
after_success:
 - docker build -t reazm/multi-client ./client
 - docker build -t reazm/multi-server ./server
 - docker build -t reazm/multi-nginx ./nginx
 - docker build -t reazm/multi-worker ./client
 
 # Log in to docker cli
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # push the docker images to docker hub
 - docker push reazm/multi-client
 - docker push reazm/multi-server
 - docker push reazm/multi-nginx
 - docker push reazm/multi-worker