sudo: required
services:
  - docker

before_install:
  - docker build -t vamaya/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true vamaya/react-test npm test -- --coverage

after_success:
  - docker build -t vamaya/multi-client ./client
  - docker build -t vamaya/multi-nginx ./nginx
  - docker build -t vamaya/multi-server ./server
  - docker build -t vamaya/multi-worker /.worker
  #Log in  to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push vamaya/multi-client
  - docker push vamaya/multi-nginx
  - docker push vamaya/multi-server
  - docker push vamaya/multi-worker

  

